### ISSUE TITLE
Why not DaoRuntimeException

### ISSUE THREAD

**Issue by zhurlik** [Brest-Java-Course-2019/Maksim-Martsiusheu#1]
https://github.com/Brest-Java-Course-2019/Maksim-Martsiusheu/blob/94e6fe0651ffaf712d30d5b60a995b114cbecd14/CourseProject/dao/src/main/java/com/epam/course/cp/dao/CategoryDaoJdbcImpl.java#L271

**Comment by MaksimMartsiusheu** [comment]
Fix at [this commit](https://github.com/Brest-Java-Course-2019/Maksim-Martsiusheu/commit/85d2300804b042e6e04cc70bcb929bfcf45696c7)

**Comment by zhurlik** [comment]
one of the sure signs of good quality code - if a logic/class was changed, the corresponding unit test should change. In your case looks like it doesn't matter which an exception you are throwing... that's bad :)

**Comment by MaksimMartsiusheu** [comment]
Add tests on showing negative results at [this commit](https://github.com/Brest-Java-Course-2019/Maksim-Martsiusheu/commit/6f664447d4692fe70c390f40dc6ef22c139b1589)
