### ISSUE TITLE
LocalDate.of()

### ISSUE THREAD

**Issue by zhurlik** [Brest-Java-Course-2019/Maksim-Martsiusheu#2]
https://github.com/Brest-Java-Course-2019/Maksim-Martsiusheu/blob/94e6fe0651ffaf712d30d5b60a995b114cbecd14/CourseProject/dao/src/test/java/com/epam/course/cp/dao/ProductDaoJdbcImplTest.java#L30

**Comment by MaksimMartsiusheu** [comment]
Fix at [this commit](https://github.com/Brest-Java-Course-2019/Maksim-Martsiusheu/commit/ee810290713998cd2c8f1be9624274272631e2b8)
