### ISSUE TITLE
Constructor injection (private final for fields)

### ISSUE THREAD

**Issue by zhurlik** [Brest-Java-Course-2019/Maksim-Martsiusheu#3]
https://docs.spring.io/spring-boot/docs/current/reference/html/using-boot-spring-beans-and-dependency-injection.html

https://github.com/Brest-Java-Course-2019/Maksim-Martsiusheu/blob/94e6fe0651ffaf712d30d5b60a995b114cbecd14/CourseProject/rest-app/src/main/java/com/epam/course/cp/rest_app/CategoryRestController.java#L45

**Comment by MaksimMartsiusheu** [comment]
Fix at [this commit](https://github.com/Brest-Java-Course-2019/Maksim-Martsiusheu/commit/4b3e78759c5ce1ca3b4818d9086df3a920ef2354)
