### ISSUE TITLE
Do you have any exception handling in spring mvc?

### ISSUE THREAD

**Issue by zhurlik** [Brest-Java-Course-2019/Maksim-Martsiusheu#4]
https://github.com/Brest-Java-Course-2019/Maksim-Martsiusheu/blob/94e6fe0651ffaf712d30d5b60a995b114cbecd14/CourseProject/rest-app/src/main/webapp/WEB-INF/root-context.xml#L17

**Comment by MaksimMartsiusheu** [comment]
Change an exception handler with SimpleMappingExceptionResolver based on WebErrorHandler in web-app and add RestErrorHandler for rest-app in [this commit](https://github.com/Brest-Java-Course-2019/Maksim-Martsiusheu/commit/e52f0dcc0084076def701522f27b7128e7045e03)
